# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - 'v*'

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24.12.0
      - run: npm i
      - run: npm ci
      - run: npm run build
      - run: npm test

  publish-npm:
    name: Publish to NPM
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24.12.0
          registry-url: https://registry.npmjs.org/
      - run: |
          npm i
          npm ci
          npm run build
      - run: npm publish -f
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  create-release:
    name: Create Release
    needs: publish-npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Extract dependency versions
      id: versions
      run: |
        PIXIJS_VERSION=$(node -p "require('./package.json').dependencies['pixi.js']")
        PIXISOUND_VERSION=$(node -p "require('./package.json').dependencies['@pixi/sound']")
        PIXIDEVTOOLS_VERSION=$(node -p "require('./package.json').dependencies['@pixi/devtools']")
        MOTION_VERSION=$(node -p "require('./package.json').dependencies['motion']")
        echo "pixijs=$PIXIJS_VERSION" >> $GITHUB_OUTPUT
        echo "pixisound=$PIXISOUND_VERSION" >> $GITHUB_OUTPUT
        echo "pixidevtools=$PIXIDEVTOOLS_VERSION" >> $GITHUB_OUTPUT
        echo "motion=$MOTION_VERSION" >> $GITHUB_OUTPUT
    - uses: ncipollo/release-action@v1
      with:
        body: |
          Release ${{ github.ref }}
          
          ### Dependencies
          - **PixiJS**: ${{ steps.versions.outputs.pixijs }}
          - **Pixi Sound**: ${{ steps.versions.outputs.pixisound }}
          - **Pixi Devtools**: ${{ steps.versions.outputs.pixidevtools }}
          - **Motion**: ${{ steps.versions.outputs.motion }}
